### ISSUE TITLE
Jackett package install script

### ISSUE THREAD

**Issue by RolluS** [QuickBox/quickbox_packages#4]
Hello,

The package is not installing because of a change in github repo page.

You should correct  this line:
jackettver=$(wget -q https://github.com/Jackett/Jackett/releases/latest -O - | grep -E \/tag\/ | awk -F "[><]" '{print $3}')
which returns "This repository v0.7.1197"

Setting jackettver manually corrects things

**Comment by RolluS** [comment]
Workaround (I don't understand awk):
jackettver=$(wget -q https://github.com/Jackett/Jackett/releases/latest -O - | grep -E /tag/ | awk -F "[><]" '{print $3}' | cut -d' ' -f3)

**Comment by d2dyno** [comment]
Already made a PR for this :) https://github.com/QuickBox/quickbox_packages/pull/3

**Comment by JMSDOnline** [comment]
This has been patched per https://github.com/QuickBox/quickbox_packages/commit/839156b937001fe16149172eb41ca6183a84ef6c. Thanks for the request @d2dyno ! 😃
