### ISSUE TITLE
Update PlexRequests to Ombi

### ISSUE THREAD

**Issue by d2dyno** [QuickBox/quickbox_packages#6]
The project name is no longer "PlexRequests.NET", it's now "Ombi", since the Plex team contacted the devs making them change their name. With update 2.2 to Ombi, all traces of PlexRequests have been removed from the program.

Let's start updating the package/QB code to reflect this change. I can start working on it soon.

**Comment by JMSDOnline** [comment]
Sounds good @d2dyno! This is something I have been meaning to work on, as we changed the repo to reflect it properly... I never adjusted the naming. :/
